echo added while server run

diff --git a/.github/workflows/playwright-scheduled.yml b/.github/workflows/playwright-scheduled.yml
--- a/.github/workflows/playwright-scheduled.yml
+++ b/.github/workflows/playwright-scheduled.yml
@@ -32,7 +32,15 @@ jobs:
         run: npx json-server db.json --port 3000  --host 0.0.0.0 &
 
       - name: Wait for mock server to be ready
-        run: npx wait-on http://127.0.0.1:3000/products
+        run: |
+          echo "Waiting for JSON server..."
+          for i in {1..15}; do
+            curl -s http://127.0.0.1:3000/products && echo "✅ Server is up!" && exit 0
+            echo "Attempt $i failed, retrying in 2s..."
+            sleep 2
+          done
+          echo "❌ Server never started"
+          exit 1
       
       - name: Run Playwright tests
         run: npx playwright test  
